### ISSUE TITLE
depends_on

### ISSUE THREAD

**Issue by matthewmueller** [carrot/terraform-api-gateway-cors-module#1]
hey thanks for putting this together, i ended up needing `depends_on` to get it to work with multiple resources:

```
resource "aws_api_gateway_integration_response" "ResourceOptionsIntegrationResponse" {
  depends_on = ["aws_api_gateway_integration.ResourceOptionsIntegration"]
  rest_api_id = "${var.rest_api_id}"
  resource_id = "${var.resource_id}"
  http_method = "${aws_api_gateway_method.ResourceOptions.http_method}"
  status_code = "200"
  response_parameters = {
    "method.response.header.Access-Control-Allow-Headers" = "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'",
    "method.response.header.Access-Control-Allow-Methods" = "'POST,OPTIONS,GET,PUT,PATCH,DELETE'",
    "method.response.header.Access-Control-Allow-Origin" = "'*'"
  }
}
```

Based on this: https://github.com/hashicorp/terraform/issues/6128

**Comment by kfloz** [comment]
Hi is CORS still not supported by hashicorp natively?  Just been looking into this issue, found this great module, but suprised not supported natively by terraform yet?  Quick check I couldnt find it?

**Comment by mdesanti** [comment]
@matthewmueller I also had to add `depends_on = ["aws_api_gateway_integration.ResourceOptionsIntegration"]` to get this working.
